#!/usr/bin/env bash
echo "OSI modeli, telekommunikasiya sistemlərinin kommunikasiya funksiyalarını, daxili struktur və texnologiyasına baxmayaraq təsvir edən konseptual modeldir."
echo "OSI modeli aşağıdan yuxarıya belə təşkil olunub: Fiziki, Data Link, Şəbəkə, Nəqliyyat, Sessiya, Təqdimat və Tətbiq."

